//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace ClassLibraryValidaArquivoCEF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AL\r<br>AP\r<br>AM\r<br>BA\r<br>CE\r<br>DF\r<br>ES\r<br>GO\r<br>MA\r<br>MT\r<br>MS\r<br>MG\r<br>PA\r<br>PB\r<br>PR\r<br>PE\r<br>PI\r<br>RJ\r<br>RN\r<br>RS\r<br>R" +
            "O\r<br>RR\r<br>SC\r<br>SP\r<br>SE")]
        public string siglaEstados {
            get {
                return ((string)(this["siglaEstados"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"001
003
004
012
021
024
025
029
031
033
036
037
040
041
045
047
062
063
064
065
069
070
072
073
074
075
078
079
081
082
083
095
096
104
107
119
125
184
204
208
214
215
217
218
222
224
230
233
237
246
248
249
250
263
265
318
320
341
356
366
370
376
389
394
394
399
409
422
453
456
464
473
477
479
487
488
492
505
600
604
610
611
612
623
626
633
634
641
643
652
653
655
707
719
739
740
745
746
747
748
749
751
752
755
756
M03
M06
M07
M08
M09
M11
M14
M16
M18
M19
M20
M22
M23
M24
")]
        public string codigoBancos {
            get {
                return ((string)(this["codigoBancos"]));
            }
        }
    }
}
